config/routes.rb
Yalile::Application.routes.draw do

  # ================ DEVISE ROUTES FOR USERS ===============================================
  devise_for :user, skip: [:sessions, :passwords]
  devise_scope :user do
    # ================ ROOT ================================================================
    root to: "user/sessions#new"
    # ================ DEVISE ROUTES =======================================================
    get "login", to: "user/sessions#new", as: "new_user_session"
    post "login", to: "user/sessions#create", as: "user_session"
    delete "logout", to: "user/sessions#destroy", as: "destroy_user_session"
  end

  # ================= PRODUCTS ROUTES ======================================================
  resources :products, only: [:index, :new, :create] do
    # =============== PRODUCT ARTICLES ROUTES ==============================================
    resources :articles, only: [:index, :show, :new, :create]
  end

  # ================ SALES ROUTES ==========================================================
  resources :sales, only: [:index, :show, :new, :create] do
    # ================ SALES TRANSACTIONS ROUTES ===========================================
    resources :sale_transactions, only: [:destroy], as: :transactions
  end

  # ================ SALES TRANSACTIONS ROUTES =============================================
  resources :sale_transactions, only: [:index], path: :"sale-transactions"

  # ================ USERS ROUTES ==========================================================
  scope module: :user do
    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put "update_profile" => "users#update_profile", on: :member, as: :update
    end
  end

  # ================ USERS REPORTS =========================================================
  resources :reports, only: :index

  # ================ ARTICLEs STOCKS =======================================================
  resources :stocks, only: :index

  # ================ INFORMATIONS ROUTES ===================================================
  get ":resource/information" => "informations#index", as: :informations
  get ":resource/:id/information" => "informations#show", as: :get_information
end
#== Route Map
# Generated on 28 Aug 2012 19:52
#
#        user_registration POST   /user(.:format)                                 devise/registrations#create
#    new_user_registration GET    /user/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                            devise/registrations#edit
#                          PUT    /user(.:format)                                 devise/registrations#update
#                          DELETE /user(.:format)                                 devise/registrations#destroy
#                     root        /                                               user/sessions#new
#         new_user_session GET    /login(.:format)                                user/sessions#new
#             user_session POST   /login(.:format)                                user/sessions#create
#     destroy_user_session DELETE /logout(.:format)                               user/sessions#destroy
#         product_articles GET    /products/:product_id/articles(.:format)        articles#index
#                          POST   /products/:product_id/articles(.:format)        articles#create
#      new_product_article GET    /products/:product_id/articles/new(.:format)    articles#new
#          product_article GET    /products/:product_id/articles/:id(.:format)    articles#show
#                 products GET    /products(.:format)                             products#index
#                          POST   /products(.:format)                             products#create
#              new_product GET    /products/new(.:format)                         products#new
#         sale_transaction DELETE /sales/:sale_id/sale_transactions/:id(.:format) sale_transactions#destroy
#                    sales GET    /sales(.:format)                                sales#index
#                          POST   /sales(.:format)                                sales#create
#                 new_sale GET    /sales/new(.:format)                            sales#new
#                     sale GET    /sales/:id(.:format)                            sales#show
#        sale_transactions GET    /sale-transactions(.:format)                    sale_transactions#index
#              update_user PUT    /users/:id/update_profile(.:format)             user/users#update_profile
#                    users GET    /users(.:format)                                user/users#index
#                          POST   /users(.:format)                                user/users#create
#                 new_user GET    /users/new(.:format)                            user/users#new
#                edit_user GET    /users/:id/edit(.:format)                       user/users#edit
#                     user GET    /users/:id(.:format)                            user/users#show
#                          PUT    /users/:id(.:format)                            user/users#update
#                  reports GET    /reports(.:format)                              reports#index
#                   stocks GET    /stocks(.:format)                               stocks#index
#             informations GET    /:resource/information(.:format)                informations#index
#          get_information GET    /:resource/:id/information(.:format)            informations#show

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  product_id  :integer
#  description :text             default(""), not null
#  size        :string(255)      not null
#  in_stock    :integer          default(0)
#  code        :string(255)      not null
#  status      :integer
#  price       :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_articles_on_code         (code) UNIQUE
#  index_articles_on_description  (description)
#  index_articles_on_size         (size)
#

class Article < ActiveRecord::Base

  paginates_per 10

  attr_accessible :code, :description, :in_stock, :product_id, :size, :status, :price

  # ASOCIATIONS
  belongs_to :product

  # VALIDATIONS
  validates_associated :product
  # validates :product_id, presence: true
  validates :description, presence: true
  validates :size, presence: true, format: {with: /^[a-z0-9]*$/i}
  validates :code, presence: true, uniqueness: true, format: {with: /^[a-z0-9]*$/i}
  validates :in_stock, presence: true, inclusion: {in: 1..100}
  validates :price, presence: true, numericality: {greater_than: 0}

  # CALLBACKS
  before_destroy AvoidDestroy

  def product_reference(attr=:id)
    self.product.send(attr)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :find_product, :only => [:index, :show, :new, :create]

  def index
    @search = @product.articles.search(params[:q])
    @articles = @search.result.page(params[:page])
    if request.xhr?
      render json: {html: render_to_string(partial: "table", layout: false)}
    end
  end
  
  def show
    @article = Article.find_by_id(params[:id])
  end
  
  def new
    @article = Article.new
    render json: {html: render_to_string(:new, layout: false)}
  end
  
  def create
    @article = @product.articles.new(params[:article])
    if @article.save
      render json: {status: "success"}
    else
      render json: {status: "error", errors: @article.errors}
    end
  end
  
  private
  
  def find_product
    @product = Product.find_by_id(params[:product_id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_filter.html.erb
<div class="box-default clearfix head-table box-app">
  <%= search_form_for @search, url: product_articles_path do |form| %>
    <div class="four-fieldset clearfix">
      <fieldset>
        <%= form.label :code_cont, "Código:" %>
        <%= form.text_field :code_cont, class: :text %>
      </fieldset>
      <fieldset class="big">
        <%= form.label :description_cont, "Referencia:" %>
        <%= form.text_field :description_cont, class: :text %>
      </fieldset>
      <fieldset>
        <%= form.label :size_cont, "Talla:" %>
        <%= form.text_field :size_cont, class: :text %>
      </fieldset>
      <fieldset class="btn-alone last">
        <%= content_tag :div, form.submit("Buscar", name: nil), class: "btn-green" %>
      </fieldset>
    </div><!-- four-fieldset clearfix END -->
  <% end %>
</div><!-- box-default clearfix head-table box-app END  -->

app/views/articles/_table.html.erb
<table class="main-table aligncenter">
  <thead>
    <tr>
      <td><span>Código</span></td>
      <td><span>Valor</span></td>
      <td><span>Talla</span></td>
      <td><span>Referencia</span></td>
      <td><span>En Bodega</span></td>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for :tr, @articles do |article| %>
      <td>
        <%= link_to "", product_article_path(params[:product_id], article.id), class: "hidden" %>
        <%= content_tag :span, article.code %>
      </td>
      <td><%= content_tag :span, number_to_currency(article.price) %></td>
      <td><%= content_tag :span, article.size %></td>
      <td><%= content_tag :span, article.description %></td>
      <td><%= content_tag :span, article.in_stock %></td>
    <% end %>
  </tbody>
</table>
<div class="navigation">
  <%= content_tag :p, page_entries_info(@articles, entry_name: "Articulos") %>
  <%= paginate @articles %>
</div>

app/views/articles/index.html.erb
<% title "Artículos" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <h2 class="floatleft">Listado De Articulos</h2>
        <%= link_to content_tag(:span, "Crear Nuevo Artículo"), new_product_article_path , id: "form_for_new_button", class: "btn-blue-icon add floatright add-app" %>
      </div>
      <div id="form_for_html_render" class="hidden box-default rounder-all-five marginbottom clearfix box-app">
      </div><!-- hidden box-default rounder-all-five marginbottom clearfix box-app END -->
      <%= render "filter" %>
      <div id="site_render_html">
        <%= render "table" %>
      </div>
      <%= link_to products_path, class: "btn-back" do %>
        <%= content_tag :span %>
        Listado Productos
      <% end %>
    </div><!--.content-main END -->
    <%= render "shared/common/footer" %>
  </div><!-- content-right clearfix END -->
</div><!-- wrapper clearfix END -->
<% javascripts "validationForms" %>

app/views/articles/new.html.erb
<%= simple_form_for [@product, @article], html: {id: "article_form"}, defaults: {input_html: {class: "text"}} do |form| %>
  <div class="four-fieldset clearfix more-separate">
    <%= render "shared/common/article_fields", form: form %>
  </div><!--.four-fieldset-->
  <div class="cancel-save">
    <ul class="list-cancel">
      <li><%= content_tag :div, form.button(:submit, value: "Guardar Articulo", id: "form_for_create_button"), class: "btn-green" %></li>
      <li><%= link_to "Cancelar", "javascript:void(0);", :class => "cancel-app", :id => "form_for_cancel_button" %></li>
    </ul><!-- list-cancel END -->
  </div><!-- cancel-save END -->
<% end %>

app/views/articles/show.html.erb
<% title "Artículo" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>  
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <h2>Detalles Del Producto</h2>
      </div>
      <div class="wrapp-box">
        <div class="box-default head-table">
          <ul class="details first-big clearfix">
            <li>
              <label><strong>ID:</strong></label>
              <%= content_tag :span, @product.id %>
            </li>
            <li>
              <label><strong>Nombre:</strong></label>
              <%= content_tag :span, @product.name.capitalize %>
            </li>
            <li>
              <label><strong>No. Artículos Asociados:</strong></label>
              <%= content_tag :span, @product.articles.count %>
            </li>
            <li>
              <label><strong>Creado En:</strong></label>
              <%= content_tag :span, formatted_time(@product.created_at) %>
            </li>
            <li>
              <label><strong>Actualizado En:</strong></label>
              <%= content_tag :span, formatted_time(@product.updated_at) %>
            </li>
          </ul>
        </div><!--.box-default-->
      </div><!--.wrapp-box-->
      
      <div class="content-title">
        <h2>Detalles Del Articulo</h2>
      </div>
      <div class="wrapp-box">
        <div class="box-default head-table">
          <ul class="details first-big clearfix">
            <li>
              <label><strong>ID:</strong></label>
              <%= content_tag :span, @article.id %>
            </li>
            <li>
              <label><strong>Código:</strong></label>
              <%= content_tag :span, @article.code %>
            </li>
            <li>
              <label><strong>Talla:</strong></label>
              <%= content_tag :span, @article.size %>
            </li>
            <li>
              <label><strong>Unidades Disponibles:</strong></label>
              <%= content_tag :span, @article.in_stock %>
            </li>
            <li>
              <label><strong>Valor:</strong></label>
              <%= content_tag :span, number_to_currency(@article.price) %>
            </li>
          </ul>
        </div><!--.box-default-->
        <div class="box-default box-bottom">
          <ul class="details first-big clearfix">
            <li class="more-width">
              <label><strong>Descripción del Artículo:</strong></label>
              <%= content_tag :span, @article.description %>
            </li>
            <li>
              <label><strong>Creado En:</strong></label>
              <%= content_tag :span, formatted_time(@article.created_at) %>
            </li>
            <li>
              <label><strong>Actualizado En:</strong></label>
              <%= content_tag :span, formatted_time(@product.updated_at) %>
            </li>
          </ul>
        </div><!--.box-default-->
      </div><!--.wrapp-box-->
      
      <div class="wrapp-box clearfix">
        <div class="two-columns floatleft box-summary">
          <h3 class="details">Product Value</h3>
          <div class="box-default rounder-all-five">
            <ul class="list-price clearfix">
              <li>
                <strong>Gross Value:</strong>
                <span>$999.999,99</span>
              </li>
              <li>
                <strong>Discount:</strong>
                <span>$999.999,99</span>
              </li>
              <li>
                <strong>Taxes:</strong>
                <span>$999.999,99</span>
              </li>
              <li>
                <strong>Fees:</strong>
                <span>$999.999,99</span>
              </li>
            </ul><!--.list-price-->
            <ul class="list-price net clearfix">
              <li>
                <strong>Net Value</strong>
                <span>$999.999,99</span>
              </li>
            </ul><!--.list-price-->
          </div><!--.box-default-->
        </div><!--.two-columns-->
        <div class="two-columns floatright box-summary">
          <h3 class="details">Product Value</h3>
          <table class="status-history">
            <tbody>
              <tr>
                <td>Date</td>
                <td>Status</td>
              </tr>
              <tr>
                <td>22 / 12 /  2011 5:43pm</td>
                <td class="table-status initiated">Initiated</td>
              </tr>
              <tr>
                <td>22 / 12 /  2011 5:43pm</td>
                <td class="table-status pending">Pending</td>
              </tr>
              <tr>
                <td>22 / 12 /  2011 5:43pm</td>
                <td class="table-status approved">Approved</td>
              </tr>
              <tr>
                <td>22 / 12 /  2011 5:43pm</td>
                <td class="table-status canceled">Canceled</td>
              </tr>
            </tbody>
          </table>
        </div><!--.two-columns-->
      </div><!--.wrapp-box-->
      <%= link_to :back, class: "btn-back" do %>
        <%= content_tag :span, "" %> Regresar
      <% end %>
    </div><!--.content-main-->
    <%= render "shared/common/footer" %>
  </div><!--.content-right-->
</div><!--.wrapper-->