config/routes.rb
Yalile::Application.routes.draw do

  # ================ DEVISE ROUTES FOR USERS ===============================================
  devise_for :user, skip: [:sessions, :passwords]
  devise_scope :user do
    # ================ ROOT ================================================================
    root to: "user/sessions#new"
    # ================ DEVISE ROUTES =======================================================
    get "login", to: "user/sessions#new", as: "new_user_session"
    post "login", to: "user/sessions#create", as: "user_session"
    delete "logout", to: "user/sessions#destroy", as: "destroy_user_session"
  end

  # ================= PRODUCTS ROUTES ======================================================
  resources :products, only: [:index, :new, :create] do
    # =============== PRODUCT ARTICLES ROUTES ==============================================
    resources :articles, only: [:index, :show, :new, :create]
  end

  # ================ SALES ROUTES ==========================================================
  resources :sales, only: [:index, :show, :new, :create] do
    # ================ SALES TRANSACTIONS ROUTES ===========================================
    resources :sale_transactions, only: [:destroy], as: :transactions
  end

  # ================ SALES TRANSACTIONS ROUTES =============================================
  resources :sale_transactions, only: [:index], path: :"sale-transactions"

  # ================ USERS ROUTES ==========================================================
  scope module: :user do
    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put "update_profile" => "users#update_profile", on: :member, as: :update
    end
  end

  # ================ USERS REPORTS =========================================================
  resources :reports, only: :index

  # ================ ARTICLEs STOCKS =======================================================
  resources :stocks, only: :index

  # ================ INFORMATIONS ROUTES ===================================================
  get ":resource/information" => "informations#index", as: :informations
  get ":resource/:id/information" => "informations#show", as: :get_information
end
#== Route Map
# Generated on 28 Aug 2012 19:52
#
#        user_registration POST   /user(.:format)                                 devise/registrations#create
#    new_user_registration GET    /user/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                            devise/registrations#edit
#                          PUT    /user(.:format)                                 devise/registrations#update
#                          DELETE /user(.:format)                                 devise/registrations#destroy
#                     root        /                                               user/sessions#new
#         new_user_session GET    /login(.:format)                                user/sessions#new
#             user_session POST   /login(.:format)                                user/sessions#create
#     destroy_user_session DELETE /logout(.:format)                               user/sessions#destroy
#         product_articles GET    /products/:product_id/articles(.:format)        articles#index
#                          POST   /products/:product_id/articles(.:format)        articles#create
#      new_product_article GET    /products/:product_id/articles/new(.:format)    articles#new
#          product_article GET    /products/:product_id/articles/:id(.:format)    articles#show
#                 products GET    /products(.:format)                             products#index
#                          POST   /products(.:format)                             products#create
#              new_product GET    /products/new(.:format)                         products#new
#         sale_transaction DELETE /sales/:sale_id/sale_transactions/:id(.:format) sale_transactions#destroy
#                    sales GET    /sales(.:format)                                sales#index
#                          POST   /sales(.:format)                                sales#create
#                 new_sale GET    /sales/new(.:format)                            sales#new
#                     sale GET    /sales/:id(.:format)                            sales#show
#        sale_transactions GET    /sale-transactions(.:format)                    sale_transactions#index
#              update_user PUT    /users/:id/update_profile(.:format)             user/users#update_profile
#                    users GET    /users(.:format)                                user/users#index
#                          POST   /users(.:format)                                user/users#create
#                 new_user GET    /users/new(.:format)                            user/users#new
#                edit_user GET    /users/:id/edit(.:format)                       user/users#edit
#                     user GET    /users/:id(.:format)                            user/users#show
#                          PUT    /users/:id(.:format)                            user/users#update
#                  reports GET    /reports(.:format)                              reports#index
#                   stocks GET    /stocks(.:format)                               stocks#index
#             informations GET    /:resource/information(.:format)                informations#index
#          get_information GET    /:resource/:id/information(.:format)            informations#show

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string(255)      default(""), not null
#  encrypted_password  :string(255)      default(""), not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0)
#  status              :integer          default(0), not null
#  fullname            :string(255)      not null
#  username            :string(255)      not null
#  is_admin            :boolean          default(FALSE)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_fullname_and_username_and_email  (fullname,username,email) UNIQUE
#


# USER STATUS [0,1,2] = [ACTIVE, APPROVED, INACTIVE]
class User < ActiveRecord::Base

  paginates_per 10

  has_many :sales
  has_many :sale_transactions, through: :sales

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable and :omniauthable, :recoverable, :trackable
  devise :database_authenticatable, :registerable, :rememberable, :validatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fullname, :is_admin, :username, :status

  # VALIDATIONS
  validates :fullname, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :status, inclusion: {in: 0..2}

  # FUNCTION TO FIND A USER THROUGH HIS USERNAME, AND COMPARE THE PASSWORD SENT
  def self.find_user(params={})
    user = find_by_username(params[:username])
    return user if !user.blank? && user.valid_password?(params[:password])
    nil
  end

  def valid_status
    return ["new", 0], ["approved", 1], ["inactive", 2]
  end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController

  def new
  end

  def create
    @user = User.find_user(params[:user])
    if @user.nil?
      flash[:error] = "Usuario o Contrasena invalida"
      render :new
    else
      sign_in(:user, @user)
      redirect_to products_path
    end
  end
  
  def destroy
    sign_out(current_user)
    redirect_to root_path
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :user_profile, only: [:update, :update_profile]

  def index    
    @search = User.search(params[:q])
    @users = @search.result.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @last_sales = @user.sale_transactions.order{created_at.desc}.limit(5)
  end

  def new
    @user = User.new
    render json: {html: render_to_string("new", layout: false)}
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @response = {status: :success}
    else
      @response = {status: :error, errors: @user.errors}
    end
    render json: @response
  end

  def edit
    @user =  User.find(params[:id])
    if request.xhr?
      render json: {html: render_to_string("admin_edit", layout: false)}
    end
  end

  def update
    if @user.update_attributes(params[:user])
      @response = {status: :success}
    else
      @response = {status: :error, errors: @user.errors}
    end
    render json: @response
  end

  def update_profile
    if @user.update_attributes(params[:user])
      flash[:success] = "Has actualizado tu perfil de forma correcta."
      redirect_to edit_user_path(@user)
    else
      flash[:error] = "Hay errores actualizando tu perfil."
      render :edit
    end
  end

  private

  def user_profile
     params[:user].delete_if{|key, value| value.blank?}
     @user = User.find(params[:id])
  end

end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/_filter.html.erb
<div class="box-default clearfix head-table box-app">
  <%= search_form_for @search do |form| %>
    <div class="four-fieldset clearfix">
      <fieldset>
        <%= form.label :username_cont, "Usuário:" %>
        <%= form.text_field :username_cont, class: :text %>
      </fieldset>
      <fieldset>
        <%= form.label :email_cont, "Email:" %>
        <%= form.text_field :email_cont, class: :text %>
      </fieldset>
      <fieldset class="btn-alone last">
        <%= content_tag :div, form.submit("Buscar", name: nil), class: "btn-green" %>
      </fieldset>
    </div><!--.box-search-filter-->
  <% end %>
</div><!-- box-default clearfix head-table box-app END -->

app/views/user/users/_table.html.erb
<table class="main-table aligncenter">
  <thead>
    <tr>
      <td><span>Status</span></td>
      <td><span>Nombre</span></td>
      <td><span>Email</span></td>
      <td><span>User</span></td>
      <td><span>Role</span></td>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for :tr, @users do |user| %>
      <td>
        <%= link_to "", user_path(user.id), class: "hidden" %>
        <%= content_tag :span, "", class: "table-status #{icon_table_helper(:class, user.status)}", title: icon_table_helper(:title, user.status) %>
      </td>
      <td><%= content_tag :span, user.fullname %></td>
      <td><%= content_tag :span, user.email %></td>
      <td><%= content_tag :span, user.username %></td>
      <td><%= content_tag :span, user.is_admin.eql?(true) ? "Admin" : "Usuário" %></td>
    <% end %>
  </tbody>
</table>
<div class="navigation">
  <%= content_tag :p, page_entries_info(@users, entry_name: "Usuários") %>
  <%= paginate @users %>
</div>

app/views/user/users/_user_fields.html.erb
<div class="four-fieldset clearfix">
  <%= form.input :status, label: "Estado", collection: @user.valid_status, input_html: {class: "skin-select"}, include_blank: false %>
  <%= form.input :fullname, label: "Nombre", wrapper_html: {class: :big}, input_html: {maxlength: 40} %>
  <%= form.input :email, label: "Email", wrapper_html: {class: "medium last"}, input_html: {maxlength: 30} %>
  <%= form.input :username, label: "Nombre de Usuário", input_html: {maxlength: 15} %>
  <%= form.input :password, label: "Contraseña", wrapper_html: {class: :big}, input_html: {maxlength: 10} %>
  <%= content_tag :fieldset do %>
    <%= content_tag :div, class: "nolabel checkbox-label floatleft" do %>
      <%= form.input(:is_admin, label: false, wrapper: false, input_html: {class: nil}) %>
      <%= form.label :is_admin, "Admin" %>
    <% end %>
  <% end %>
</div><!--.four-fieldset clearfix END -->

app/views/user/users/admin_edit.html.erb
<%= simple_form_for @user, html: {id: "user_form"}, defaults: {input_html: {class: "text"}} do |form| %>
  <%= render "user_fields", form: form %>
  <div class="cancel-save">
    <ul class="list-cancel">
      <li><%= content_tag :div, form.button(:submit, value: "Guardar Usuário", id: "form_for_update_button") , class: "btn-green" %></li>
      <li><%= link_to "Cancelar", "javascript:void(0);", class: "canel-app", id: "form_for_cancel_button" %></li>
    </ul>
  </div>
<% end %>

app/views/user/users/edit.html.erb
<% title "Mi Perfil" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <%= content_tag :div, content_tag(:h2, "Editar Perfil"), class: "content-title" %>
      <div class="wrapp-box">
        <div class="two-columns">
          <div class="box-default head-table clearfix">
            <%= simple_form_for @user, url: update_user_path(params[:id]), html: {id: "user_form"}, defaults: {input_html: {class: "text"}} do |form| %>
              <%= form.input :fullname, label: "Nombre Completo", input_html: {maxlength: 40} %>
              <%= form.input :email, label: "Email", input_html: {maxlength: 30} %>
              <%= form.input :username, label: "Usuário", input_html: {maxlength: 15} %>
              <%= form.input :password, label: "Contraseña", input_html: {maxlength: 10, value: ""} %>
              <%= form.input :password_confirmation, label: "Confirmar Contraseña", wrapper_html: {class: "marginbottom"}, input_html: {maxlength: 10} %>
              <%= content_tag :div, form.button(:submit, value: "Guardar"), class: "btn-green floatright" %>
            <% end %>
          </div><!-- box-default head-table clearfix END -->
        </div><!-- two-columns END -->
      </div><!-- wrapp-box END -->
    </div><!-- content-main clearfix END -->
    <%= render "shared/common/footer" %>
  </div><!-- content-right clearfix END -->
</div><!-- wrapper clearfix END  -->
<% javascripts "validationForms" %>

app/views/user/users/index.html.erb
<% title "Usuários" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <%= content_tag :h2, "Listado De Usuarios", class: :floatleft %>
        <%= link_to content_tag(:span, "Crear Nuevo Usuário"), new_user_path , id: "form_for_new_button", class: "btn-blue-icon add floatright add-app" %>
      </div>
      <%= content_tag :div, "", class: "hidden box-default rounder-all-five marginbottom clearfix box-app", id: "form_for_html_render" %>
      <%= render "filter" %>
      <div id="site_render_html">
        <%= render "table" %>
      </div><!-- site_render_html END -->
    </div><!--.content-main END -->
    <%= render "shared/common/footer" %>
  </div><!-- content-right clearfix END -->
</div><!-- wrapper clearfix END -->
<% javascripts "validationForms" %>

app/views/user/users/new.html.erb
<%= simple_form_for @user, html: {id: "user_form"}, defaults: {input_html: {class: "text"}} do |form| %>
  <div class="four-fieldset clearfix">
    <%= form.input :status, collection: @user.valid_status, input_html: {class: "skin-select"}, include_blank: false %>
    <%= form.input :fullname, label: "Nombre", wrapper_html: {class: :big}, input_html: {maxlength: 40} %>
    <%= form.input :email, label: "Email", wrapper_html: {class: "medium last"}, input_html: {maxlength: 30} %>
    <%= form.input :username, label: "Nombre de Usuário", input_html: {maxlength: 15} %>
    <%= form.input :password, label: "Contraseña", wrapper_html: {class: :big}, input_html: {maxlength: 6} %>
    <%= content_tag :fieldset do %>
      <%= content_tag :div, class: "nolabel checkbox-label floatleft" do %>
        <%= form.input(:is_admin, label: false, wrapper: false, input_html: {class: nil}) %>
        <%= form.label :is_admin, "Admin" %>
      <% end %>
    <% end %>
  </div><!--.four-fieldset clearfix END -->
  <div class="cancel-save">
    <ul class="list-cancel">
      <li><%= content_tag :div, form.button(:submit, value: "Guardar Usuário", id: "form_for_create_button") , class: "btn-green" %></li>
      <li><%= link_to "Cancelar", "javascript:void(0);", class: "canel-app", id: "form_for_cancel_button" %></li>
    </ul>
  </div>
<% end %>

app/views/user/users/show.html.erb
<% title "Detalles del Usuário" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <%= content_tag :div, class: "content-title"  do %>
        <%= content_tag :h2, "Detalles Del Usuário", class: "floatleft" %>
        <%= link_to "Editar", edit_user_path(@user.id), class: "btn-edit floatright", id: "form_for_edit_button" %>
      <% end %>
      <%= content_tag :div, "", class: "hidden box-default rounder-all-five marginbottom clearfix box-app", id: "form_for_html_render" %>
      <div class="wrapp-box">
        <div class="box-default head-table">
          <ul class="details first-big clearfix">
            <li>
              <label><strong>Nombre Completo:</strong></label>
              <%= content_tag :span, @user.fullname %>
            </li>
            <li>
              <label><strong>Email:</strong></label>
              <%= content_tag :span, @user.email %>
            </li>
            <li>
              <label><strong>Nombre de Usuário:</strong></label>
              <%= content_tag :span, @user.username %>
            </li>
            <li>
              <label><strong>Role:</strong></label>
              <%= content_tag :span, @user.is_admin.eql?(true) ? "Administrador" : "Usuário" %>
            </li>
            <li>
              <label><strong>Creado En:</strong></label>
              <%= content_tag :span, formatted_time(@user.created_at) %>
            </li>
          </ul>
        </div><!--.box-default-->
        <div class="box-default box-bottom">
          <ul class="details first-big clearfix">
            <li>
              <label><strong>Estado Actual:</strong></label>
              <%= content_tag :span, icon_table_helper(:title, @user.status) %>
            </li>
          </ul>
        </div><!--.box-default-->
      </div><!--.wrapp-box-->
      
      <div class="wrapp-box clearfix">
        <div class="two-columns floatleft box-summary">
          <%= content_tag :h3, "Últimas Ventas Del Usuário", class: :details %>
          <table class="status-history">
            <tbody>
              <tr>
                <td>Fecha</td>
                <td>Total Venta</td>
              </tr>
              <%= content_tag_for :tr, @last_sales do |last_sale| %>
                <%= content_tag :td, formatted_time(last_sale.created_at) %>
                <%= content_tag :td, number_to_currency(last_sale.article_total_price) %>
              <% end %>
            </tbody>
          </table>
        </div><!--.two-columns-->
      </div><!--.wrapp-box-->
      <%= link_to users_path, class: "btn-back" do %>
        <%= content_tag :span, "" %> Regresar
      <% end %>
    </div><!--.content-main-->
    <%= render "shared/common/footer" %>
  </div><!--.content-right-->
</div><!-- wrapper clerarfix END -->
<% javascripts "validationForms" %>