config/routes.rb
Yalile::Application.routes.draw do

  # ================ DEVISE ROUTES FOR USERS ===============================================
  devise_for :user, skip: [:sessions, :passwords]
  devise_scope :user do
    # ================ ROOT ================================================================
    root to: "user/sessions#new"
    # ================ DEVISE ROUTES =======================================================
    get "login", to: "user/sessions#new", as: "new_user_session"
    post "login", to: "user/sessions#create", as: "user_session"
    delete "logout", to: "user/sessions#destroy", as: "destroy_user_session"
  end

  # ================= PRODUCTS ROUTES ======================================================
  resources :products, only: [:index, :new, :create] do
    # =============== PRODUCT ARTICLES ROUTES ==============================================
    resources :articles, only: [:index, :show, :new, :create]
  end

  # ================ SALES ROUTES ==========================================================
  resources :sales, only: [:index, :show, :new, :create] do
    # ================ SALES TRANSACTIONS ROUTES ===========================================
    resources :sale_transactions, only: [:destroy], as: :transactions
  end

  # ================ SALES TRANSACTIONS ROUTES =============================================
  resources :sale_transactions, only: [:index], path: :"sale-transactions"

  # ================ USERS ROUTES ==========================================================
  scope module: :user do
    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put "update_profile" => "users#update_profile", on: :member, as: :update
    end
  end

  # ================ USERS REPORTS =========================================================
  resources :reports, only: :index

  # ================ ARTICLEs STOCKS =======================================================
  resources :stocks, only: :index

  # ================ INFORMATIONS ROUTES ===================================================
  get ":resource/information" => "informations#index", as: :informations
  get ":resource/:id/information" => "informations#show", as: :get_information
end
#== Route Map
# Generated on 28 Aug 2012 19:52
#
#        user_registration POST   /user(.:format)                                 devise/registrations#create
#    new_user_registration GET    /user/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /user/edit(.:format)                            devise/registrations#edit
#                          PUT    /user(.:format)                                 devise/registrations#update
#                          DELETE /user(.:format)                                 devise/registrations#destroy
#                     root        /                                               user/sessions#new
#         new_user_session GET    /login(.:format)                                user/sessions#new
#             user_session POST   /login(.:format)                                user/sessions#create
#     destroy_user_session DELETE /logout(.:format)                               user/sessions#destroy
#         product_articles GET    /products/:product_id/articles(.:format)        articles#index
#                          POST   /products/:product_id/articles(.:format)        articles#create
#      new_product_article GET    /products/:product_id/articles/new(.:format)    articles#new
#          product_article GET    /products/:product_id/articles/:id(.:format)    articles#show
#                 products GET    /products(.:format)                             products#index
#                          POST   /products(.:format)                             products#create
#              new_product GET    /products/new(.:format)                         products#new
#         sale_transaction DELETE /sales/:sale_id/sale_transactions/:id(.:format) sale_transactions#destroy
#                    sales GET    /sales(.:format)                                sales#index
#                          POST   /sales(.:format)                                sales#create
#                 new_sale GET    /sales/new(.:format)                            sales#new
#                     sale GET    /sales/:id(.:format)                            sales#show
#        sale_transactions GET    /sale-transactions(.:format)                    sale_transactions#index
#              update_user PUT    /users/:id/update_profile(.:format)             user/users#update_profile
#                    users GET    /users(.:format)                                user/users#index
#                          POST   /users(.:format)                                user/users#create
#                 new_user GET    /users/new(.:format)                            user/users#new
#                edit_user GET    /users/:id/edit(.:format)                       user/users#edit
#                     user GET    /users/:id(.:format)                            user/users#show
#                          PUT    /users/:id(.:format)                            user/users#update
#                  reports GET    /reports(.:format)                              reports#index
#                   stocks GET    /stocks(.:format)                               stocks#index
#             informations GET    /:resource/information(.:format)                informations#index
#          get_information GET    /:resource/:id/information(.:format)            informations#show

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id             :integer          not null, primary key
#  user_id        :integer          not null
#  total_articles :integer          not null
#  total          :float            not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_sales_on_user_id  (user_id)
#

class Sale < ActiveRecord::Base

  paginates_per 10

  # ASSOCIATIONS
  belongs_to :user
  has_many :sale_transactions
  has_many :articles, :through => :sale_transactions

  accepts_nested_attributes_for :sale_transactions
  attr_accessible :user_id, :total, :total_articles, :sale_transactions_attributes

  # VALIDATIONS
  validates :user_id, presence: true
  validates :total_articles, presence: true
  validates :total, presence: true

  # CALLBACKS
  before_destroy AvoidDestroy

  def transactions_by_status(current_status=0)
    self.sale_transactions.where{status == current_status}
  end

  def salesman
    self.user.username
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @search = Sale.search(params[:q])
    @sales =  @search.result.page(params[:page])
    if request.xhr?
      render json: {html: render_to_string(partial: "table")}
    end
  end

  def show
    @sale = Sale.find_by_id(params[:id])
    @saletransactions = @sale.transactions_by_status(0)
    @refundsaletransactions = @sale.transactions_by_status(1)
  end

  def new
    @articles = Article.where{in_stock > 0}
    @sale = Sale.new
    @sale.sale_transactions.build
  end

  def create
    @sale = Sale.new(params[:sale].merge!(user_id: current_user.id))
    SalesControl.complete_sale(@sale)
    if @sale.save
      SalesControl.reduce_article_stock(@sale)
      redirect_to @sale
    else
      redirect_to new_sale_path
    end
  end

end

app/helpers/sales_helper.rb
module SalesHelper

  def link_to_add_sale(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, 'javascript:void(0);', class: "add-article cancel-app", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def articles_list(saletransactions, sale=nil)
    list_html = ""
    saletransactions.each_with_index do |saletransaction, index|
      list_html.concat(content_tag(:div, class: details_articles_sale(saletransactions, index)) do
        concat(content_tag(:ul, class: "texter-list") do
          concat(content_tag :li, saletransaction.quantity_articles.to_s + " " + article_label(saletransaction.article_associated))
          concat(content_tag :li, link_to("Devolver", sale_transaction_path(sale, saletransaction), class: :remove, method: :delete)) if saletransaction.status.eql?(0)
        end)
      end)
    end
    list_html.html_safe
  end

  def details_articles_sale(saletransactions, index)
    div_class = "box-default"
    case index
    when 0
      div_class.concat(" head-table")
    when saletransactions.size - 1
      div_class.concat(" box-bottom")
    else
      div_class.concat(" box-center")
    end
  end

end

app/views/sales/_filter.html.erb
<div class="box-default clearfix head-table box-app">
  <%= search_form_for @search do |form| %>
    <div class="four-fieldset clearfix">
      <fieldset>
        <%= form.label :user_username_cont, "Vendedor:" %>
        <%= form.text_field :user_username_cont, class: :text %>
      </fieldset>
      <fieldset>
        <%= form.label :total_gteq, "Valor Desde:" %>
        <%= form.text_field :total_gteq, class: :text %>
      </fieldset>
      <fieldset>
        <%= form.label :total_lteq, "Valor Hasta:" %>
        <%= form.text_field :total_lteq, class: :text %>
      </fieldset>
      <fieldset class="btn-alone last">
        <%= content_tag :div, form.submit("Buscar", name: nil), class: "btn-green" %>
      </fieldset>
    </div><!-- box-search-filter clearfix END -->
    <div class="four-fieldset clearfix">
      <fieldset>
        <%= form.label :created_at_gteq, "Desde:" %>
        <%= form.text_field :created_at_gteq, class: "datepicker text", placeholder: "DD / MM / YYYY", readonly: true %>
      </fieldset>
      <fieldset>
        <%= form.label :created_at_lteq, "Hasta:" %>
        <%= form.text_field :created_at_lteq, class: "datepicker text", placeholder: "DD / MM / YYYY", readonly: true %>
      </fieldset>
    </div><!-- box-search-filter clearfix END -->
  <% end %>
</div><!-- head-table box-default clearfix END -->

app/views/sales/_header_actions.html.erb
<div class="<%= class_div %>">
  <ul class="list-cancel">
    <li><%= content_tag :div, form.submit("Guardar Venta"), class: "btn-green"%></li>
    <li><%= link_to_add_sale "Agregar Artículo", form, :sale_transactions %></li>
  </ul>
</div><!-- cancel-save END -->

app/views/sales/_sale_information.html.erb
<div class="wrapp-box clearfix">
  <div class="two-columns floatleft box-summary">
    <h3 class="details">Total de la Venta</h3>
    <div class="box-default rounder-all-five">
      <ul class="list-price clearfix">
        <li>
          <strong>Total Artículos:</strong>
          <span id="total_of_articles">0</span>
        </li>
      </ul><!-- .list-price clearfix END -->
      <ul class="list-price net clearfix">
        <li>
          <strong>Total Venta:</strong>
          <span id="total_of_sale">$ 0,00</span>
        </li>
      </ul><!-- .list-price net clearfix END -->
    </div><!-- .box-default rounder-all-five END -->
  </div><!-- .two-columns -->
</div><!-- wrapp-box clearfix END -->

app/views/sales/_sale_transaction_fields.html.erb
<div class="four-fieldset clearfix">
  <%= f.input :article_id, label: "Productos:", collection: @articles, value_method: "id", label_method: Proc.new{|article| article_label(article)}, prompt: "Producto", input_html: {class: "skin-select", onChange: "saleAction.articleBasicInfo(this);"}, wrapper: nil %>
  <%= f.input :quantity_articles, label: "Cantidad:", as: "string", input_html: {maxlength: 2, class: "text mnumeric"} %>
  <%= f.input :article_unit_price_sold, label: "$ Unitario:", as: "string", input_html: {disabled: true, class: "text"} %>
  <%= f.input :article_total_price, label: "$ Total:", as: "string", input_html: {disabled: true, class: "text"} %>
  <%= content_tag :ul, class: "texter-list", style: "float: left; margin-top: 32px; width: 14px;" do %>
    <%= content_tag :li, link_to("", "javascript:void(0);", class: :remove ) %>
  <% end %>
</div><!--.four-fieldset-->

app/views/sales/_table.html.erb
<table class="main-table aligncenter">
  <thead>
    <tr>
      <td><span>Código</span></td>
      <td><span>Vendedor</span></td>
      <td><span>Fecha</span></td>
      <td><span>Unidades Devueltas</span></td>
      <td><span>Unidades Vendidas</span></td>
      <td><span>Total Venta</span></td>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for :tr, @sales do |sale| %>
      <td>
        <%= link_to "", sale_path(sale.id), class: "hidden" %>
        <%= content_tag :span, sale.id %>
      </td>
      <td><%= content_tag :span, sale.salesman %></td>
      <td><%= content_tag :span, formatted_time(sale.created_at) %></td>
      <td><%= content_tag :span, sale.transactions_by_status(1).count %></td>
      <td><%= content_tag :span, sale.total_articles %></td>
      <td><%= content_tag :span, number_to_currency(sale.total) %></td>
    <% end %>
  </tbody>
</table>
<div class="navigation">
  <%= content_tag :p, page_entries_info(@sales, entry_name: "Ventas") %>
  <%= paginate @sales %>
</div>

app/views/sales/index.html.erb
<% title "Ventas" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <h2 class="floatleft">Listado De Ventas</h2>
      </div>
      <%= render "filter" %>
      <div id="site_render_html">
        <%= render "table" %>
      </div><!-- site_render_html END -->
    </div><!--.content-main END -->
    <%= render "shared/common/footer" %>
  </div><!-- content-right clearfix END -->
</div><!-- wrapper clearfix END -->

app/views/sales/new.html.erb
<% title "Nueva Venta" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <h2 class="floatleft">Nueva Venta</h2>
      </div>
      <div class="box-default rounder-all-five marginbottom clearfix box-app">
        <%= simple_form_for @sale, html: {id: "sale_form"}, defaults: {input_html: {class: "text"}} do |form| %>
          <%= render "header_actions", form: form, class_div: "" %>
          <%= form.simple_fields_for :sale_transactions do |builder| %>
            <%= render "sale_transaction_fields", f: builder %>
          <% end %>
          <%= render "header_actions", form: form, class_div: "cancel-save"  %>
        <% end %>
      </div><!-- box-default rounder-all-five marginbottom clearfix box-app END -->
      <%= render "sale_information" %>
      <%= link_to :back, class: "clear btn-back" do %>
        <%= content_tag :span %> Atras
      <% end %>
    </div><!--.content-main END -->
    <%= render "shared/common/footer" %>
  </div><!-- content-right clearfix END -->
</div><!-- wrapper clearfix END -->
<% javascripts "saleAction" %>

app/views/sales/show.html.erb
<% title "Detalles Venta" %>
<div class="wrapper clearfix">
  <%= render "shared/common/leftpanel" %>
  <div class="content-right clearfix">
    <div class="content-main clearfix">
      <div class="content-title">
        <%= content_tag :h2, "Venta Detallada", class: :floatleft %>
      </div>
      <%#= link_to "Edit", "javascript:void(0);", class: "btn-edit floatright" %>
      <div class="wrapp-box">
        <div class="box-default head-table">
          <ul class="details first-big clearfix">
            <li>
              <%= content_tag :label, content_tag(:strong, "Código") %>
              <%= content_tag :span, @sale.id %>
            </li>
            <li>
              <%= content_tag :label, content_tag(:strong, "Usuário del Vendedor") %>
              <%= content_tag :span, @sale.salesman %>
            </li>
            <li>
              <%= content_tag :label, content_tag(:strong, "Fecha de la Venta") %>
              <%= content_tag :span, formatted_time(@sale.created_at) %>
            </li>
            <li>
              <%= content_tag :label, content_tag(:strong, "Unidades Vendidas") %>
              <%= content_tag :span, @saletransactions.sum(:quantity_articles) %>
            </li>
            <li>
              <%= content_tag :label, content_tag(:strong, "Total De la Venta") %>
              <%= content_tag :span, number_to_currency(@sale.total) %>
            </li>
          </ul><!-- details first-big clearfix END -->
        </div><!--box-default head-table END -->
        <div class="box-default box-bottom">
          <ul class="details clearfix">
            <li>
              <%= content_tag :label, content_tag(:strong, "Unidades Devueltas") %>
              <%= content_tag :span, @refundsaletransactions.sum(:quantity_articles) %>
            </li>
          </ul>
        </div><!--.box-default-->
      </div><!--.wrapp-box-->
      <div class="wrapp-box clearfix">
        <div class="two-irregularbox">
          <div class="small floatleft">
            <%= content_tag :h3, "Detalle Unidades Vendidas", class: :details %>
            <%= articles_list @saletransactions, @sale %>
          </div><!-- .small floatleft END -->
          <div class="small floatright">
            <%= content_tag :h3, "Detalle Unidades Devueltas", class: :details %>
            <%= articles_list @refundsaletransactions %>
          </div><!-- .small floatright END -->
        </div><!--.two-irreguralbox-->
      </div><!--.wrapp-box-->
      <%= link_to content_tag(:span) + "Ventas", sales_path, class: "btn-back" %>
    </div><!--.content-main-->
    <%= render "shared/common/footer" %>
  </div><!--.content-right-->
</div><!-- wrapper clearfix END -->